version: '3.7'

services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "9883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ./mytb-data:/data  # Using relative paths for data
      - ./mytb-logs:/var/log/thingsboard  # Using relative paths for logs
      - ./culture_imager_rule_chain.json:/etc/thingsboard/culture_imager_rule_chain.json  # Using relative path for rule chain file
    entrypoint: >
      /bin/bash -c "
      # Start ThingsBoard in the background
      /usr/bin/java -Duser.home=/etc/thingsboard -jar /usr/share/thingsboard/bin/thingsboard.jar & 
      # Wait for ThingsBoard to start
      sleep 20 &&
      # Import the rule chain as the root rule chain
      curl -X POST -d @/etc/thingsboard/culture_imager_rule_chain.json \
        -H 'Content-Type: application/json' \
        -H 'Authorization: Bearer $TB_ACCESS_TOKEN' \
        http://localhost:8080/api/ruleChains/ && 
      # Keep the container running
      tail -f /dev/null
    "
